name: A Demo Workflow
on: push
jobs:
  build-jobs:
      name: Hello World Actions
      runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v1
         name: Checkout Code 
       - name: Echo Demo
         run: echo Hello World
       - name: Index.html Content
         run: cat index.html         

